# Generated by Django 6.0.2 on 2026-04-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_run_error_message_run_result_json_run_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='column_mapping',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
